1. Write a Python Program to find sum of array?

In [1]:
import numpy as np

In [7]:
mat1=np.matrix([[1,2],[3,4]])
mat2=np.matrix([[5,6],[7,8]])
mat1+mat2

matrix([[ 6,  8],
        [10, 12]])

2. Write a Python Program to Multiply Two Matrices?

In [8]:
mat1=np.matrix([[1,2],[3,4]])
mat2=np.matrix([[5,6],[7,8]])
mat1*mat2


matrix([[19, 22],
        [43, 50]])

3. Write a Python Program to Transpose a Matrix?

In [10]:
mat1=np.matrix([[1,2],[3,4]])
mat1



matrix([[1, 2],
        [3, 4]])

In [11]:
mat1.T

matrix([[1, 3],
        [2, 4]])

4. Write a Python Program to Sort Words in Alphabetic Order?

In [26]:
def sort(para):
    return sorted(para.split(" "))

In [27]:
sort("i am a student of ineuron data science course")

['a', 'am', 'course', 'data', 'i', 'ineuron', 'of', 'science', 'student']

5. Write a Python Program to Remove Punctuation From a String?

In [47]:
def removepunctuation(s):
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    p=''
    for i in s:
        if i not in punctuations:
            p=p+i
    return p
    
  

In [48]:
removepunctuation("amanc-&ja")


'amancja'